### ISSUE TITLE
T-Display-S3

### ISSUE THREAD

**Issue by yltsa** [Sensirion/sensihub-demo#1]
Hi. please can you update your project for the new LilyGo T-Display-S3

https://github.com/Xinyuan-LilyGO/T-Display-S3

Tnak you very much for the nice sensor projects here.

**Comment by psachs** [comment]
Hi @yltsa 

Depending on the display in use, a different version of the TFT library is required and a slightly different configuration is needed.
We already got this version working on a LilyGo T-Display S3 and I will forward your request to the responsible person. Due to holiday absences I am not sure how long it will take us to update the repository.

Thank you very much for your feedback

**Comment by yltsa** [comment]
Thanks for the info.

**Comment by yltsa** [comment]
Hi, it is working ;-)

- LilyGo T-Display-S3
- Sensirion SCD41 
- MQTT and Sensirion BLE Gadget library for publishing the data

![_M4I3892](https://user-images.githubusercontent.com/7629996/209545820-8e755be5-bcc8-486d-bd6c-dce0beb36932.jpg)

**Comment by psachs** [comment]
Thanks for the heads up, great to see you got everything working
